platform :ios, '7.0'
pod 'FMDB'
pod "AFNetworking", "~> 2.0"
pod 'RDVTabBarController'
pod 'YTKNetwork'
pod 'YTKKeyValueStore'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'KVOController'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~>3.7'
pod 'IQKeyboardManager'
pod 'ReactiveCocoa' , '2.5'